### ISSUE TITLE
Get old user-agents

### ISSUE THREAD

**Issue by ihorvasilets** [intoli/user-agents#17]
Currently the module generates mostly latest user-agents. Is there any possibility to get random old user-agents?

**Comment by sangaline** [comment]
You can get older user agents by installing an older version of the package. The full listing of versions is available on [npm](https://www.npmjs.com/package/user-agents). It would take a lot of additional storage to include the historical probability distributions and user agents, so I don't think it makes sense to pull this functionality into the library itself.
