### ISSUE TITLE
Building is failling since one moth ago 

### ISSUE THREAD

**Issue by secano9705** [intoli/user-agents#19]
It seems like the data has not been actualized since one month ago, there is a problem with the CI pipeline, check it out, please.

**Comment by LineageH** [comment]
The issue in "ga-api" package @sangaline 
Hope this will help.

**Comment by Niek** [comment]
@sangaline any chance to get this package building again?

**Comment by sangaline** [comment]
Sorry for the delay on getting things fixed up. The new `user-agents@1.0.561` release should include the latest data, and nightly releases should be working again.
