### ISSUE TITLE
Old user agents supplied

### ISSUE THREAD

**Issue by wizehood** [intoli/user-agents#22]
I'm having issues with latest version of your package.
The following snippet gives me Chrome version that are <80
```javascript
const ua = new UserAgent({ deviceCategory: "desktop" })
const userAgents = Array(100).fill().map(() => ua().toString())
```
I tried with `ua(/Chrome\/83/)` to get the newest version, but the filter won't apply. Any help?

Thanks

**Comment by janisblaus** [comment]
Agree! :) Would be great to update the database.

**Comment by zozo1237** [comment]
@sangaline

**Comment by sangaline** [comment]
Sorry for the delay on getting things fixed up. The new `user-agents@1.0.561` release should include the latest data, and nightly releases should be working again.
