### ISSUE TITLE
Update user agent data

### ISSUE THREAD

**Issue by Simobain** [intoli/user-agents#26]
" Unlike other random user agent generation libraries, the User-Agents package is updated automatically on a daily basis." 

On NPM, however it does not seem to have been updated for a while.

Could you update de data ?
Thanks :)

**Comment by NikolaiT** [comment]
any idea for a replacement module, since this is obviously outdated?

**Comment by HugoPoi** [comment]
Working on it here : https://www.npmjs.com/package/@monibrand/user-agents
But my data-set is small, so I have a good recent user-agents set but not very well distributed
My fork is a beta and break the compatibility because babel export weirdiness

**Comment by LeMoussel** [comment]
You can grabs up to date `useragent` from https://fake-useragent.herokuapp.com/browsers/0.1.11
It's data from [Python fake-useragent](https://github.com/hellysmile/fake-useragent)

**Comment by HugoPoi** [comment]
The data I have is a lot more accurate than this because I have the classification done by Google Analytics built in, I put the needed tracking dimension on my websites. But yes maybe I could write a script to import and classify other source of data.

**Comment by Andriy2** [comment]
@sangaline any updates?

**Comment by PureSwap** [comment]
I would love to see an updated user-agent list.

**Comment by zeglin** [comment]
An update on this would be awesome. The user-agent list is now rather outdated. Can we somehow think about integrating it with https://developers.whatismybrowser.com/useragents/explore/ ?

**Comment by LeMoussel** [comment]
Their database is not free of charge (50$ USD)
https://developers.whatismybrowser.com/useragents/database/

**Comment by sangaline** [comment]
Sorry for the delay on getting things fixed up. The new `user-agents@1.0.561` release should include the latest data, and nightly releases should be working again.

There are some challenges with pulling in data from other sources because most public datasets don't have the same fingerprinting fields. I would be open to combining data from multiple sites into a single dataset if anybody is interested in that. @HugoPoi it sounds like you're already collecting data yourself?

**Comment by HugoPoi** [comment]
@sangaline I confirmed I'm collecting user agents with the same Google Analytics scripts as Intoli on some of our corporate websites !
