### ISSUE TITLE
What is `Number` in UserAgent filter?

### ISSUE THREAD

**Issue by LeMoussel** [intoli/user-agents#4]
In API documentation: [`class: UserAgent([filters])`](https://github.com/intoli/user-agents#class-useragentfilters)

> filters <Array, Function, Number, Object, RegExp, or String> - A set of filters to apply to the generated user agents.

What is `Number`?

**Comment by sangaline** [comment]
This appears to have been a mistake in the API documentation which has now been corrected. Numbers aren't parsed as valid filters.
