### ISSUE TITLE
how would this be implemented in puppeteer?

### ISSUE THREAD

**Issue by hiamlegend** [intoli/user-agents#6]
I'm trying to get this implemented with puppeteer, what am I doing wrong?

`const UserAgent = require('user-agents');`
`//  set UserAgent`
`const userAgent = new UserAgent();`
`await page.setUserAgent(userAgent);`

getting this error

> (node:19627) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.setUserAgentOverride): Invalid parameters userAgent: string value expected

**Comment by HeberGB** [comment]
try
```
await page.setUserAgent(userAgent.toString());```

**Comment by hiamlegend** [comment]
@HeberGB thank you, that fixed it for me
