### ISSUE TITLE
Use of the UA JSON file in another package

### ISSUE THREAD

**Issue by sebastian-correa** [intoli/user-agents#79]
Hey @AceFire6 and @sangaline. Thank you and Intoli for your work in this package; even though I don't use it, I know it fills a crucial role!

I'm a newly appointed maintainer to the [fake-useragent](https://github.com/fake-useragent/fake-useragent) Python package, which does more or less the same thing as `user-agents` does: provide a frequently updated list of UAs and a thin interface to get random ones with filters. We're currently struggling to source up-to-date UAs, as most websites that host DBs do so "privately" and impose stringent limits to scrapers (which makes sense). I bumped across your package searching around to see how similar projects had solved this issue.

In the [LICENSE](https://github.com/intoli/user-agents/blob/main/LICENSE), you guys say that anyone can redistribute the package as long as they include a copy of the notice. I would imagine that the JSON file isn't source-code, so I'm not sure that bit applies.

Would it be okay with you if we used your JSON file from each release to feed our Python package, at least until we figure out a robust, independent way of obtaining this information? If so, what are the requirements for this, licence wise? My plan is to just get it from GitHub.

**Comment by melroy89** [comment]
OK, well no response. So we assume it's OK. 

The clause licenses (your project) are considered compatible with the Apache 2.0 (our project). So license wise I don't see any issues either.

**Comment by AceFire6** [comment]
@sebastian-correa @melroy89 I'm not affiliated with the project directly so unfortunately I can't give an answer to the licensing issues. If the projects license doesn't prevent that usage then I don't see an issue unless intoli say otherwise 🤷
